name: dotnet-workflow

on:
  push:
    branches: main # [ main ]
  pull_request:
    branches: main # [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-dotnet-app:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: Backend/EstateApp

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
  
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
